version: "3"
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-latest}
        - NODE_VERSION=${NODE_VERSION:-latest}
    image: laravel-php:${PHP_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - app

  # Mysql Service
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:${MYSQL_VERSION:-latest}
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - dbdata:/var/lib/mysql
      # Enable this if you want to restore any sql file and keep file on the same path.
      # - ./docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-default_db}
      MYSQL_USER: ${DB_USERNAME:-default_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-changeme}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-no}
    healthcheck:
      test: mysqladmin ping -h localhost -u $$DB_USERNAME --password=$$DB_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: /phpmyadmin/
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 100M
      PMA_PMADB: pmadb
    depends_on:
      - mysql
    networks:
      - app
    links:
      - mysql

  # MailPit Service
  mails:
    image: "axllent/mailpit:${MAILPIT_VERSION:-latest}"
    container_name: "${COMPOSE_PROJECT_NAME}-mailpit"
    restart: unless-stopped
    environment:
      MP_WEBROOT: /mails/
    networks:
      - app

# Network
networks:
  app:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
