apiVersion: batch/v1
kind: CronJob
metadata:
  name: laravel-scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: laravel-scheduler
            # image: laravel-php:8.2
            image: jainrounak6/laravel-sampleapp:app
            imagePullPolicy: IfNotPresent
            command:
              - php
            args:
              - artisan
              - schedule:run
            env:
              - name: APP_ENV
                value: production
              - name: QUEUE_CONNECTION
                value: database  # Adjust based on your queue driver
              - name: DB_CONNECTION
                value: mysql
              - name: DB_HOST
                value: mysql-service
              - name: DB_PORT
                value: "3306"
              - name: DB_DATABASE
                value: laravel
              - name: DB_USERNAME
                value: laravel
              - name: DB_PASSWORD
                value: laravel
              - name: APP_KEY
                value: "base64:96VAhksu++QGhaUWBtCWUSNEkwqeJMA1YHh7h41HpS0="
          restartPolicy: OnFailure
