apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-queue-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-queue-worker
  template:
    metadata:
      labels:
        app: laravel-queue-worker
    spec:
      containers:
      - name: laravel-queue-worker
        # image: laravel-php:8.2
        image: jainrounak6/laravel-sampleapp:app
        imagePullPolicy: IfNotPresent
        command:
          - php
        args:
          - artisan
          - queue:work
          - database
          - --tries=3 #Laravel default value for retry job
          # - --max-jobs=200
        resources: {}
        env:
          - name: QUEUE_CONNECTION
            value: database  # Adjust based on your queue driver
          - name: DB_CONNECTION
            value: mysql
          - name: DB_HOST
            value: mysql-service
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: laravel
          - name: DB_USERNAME
            value: laravel
          - name: DB_PASSWORD
            value: laravel
          - name: APP_KEY
            value: "base64:96VAhksu++QGhaUWBtCWUSNEkwqeJMA1YHh7h41HpS0="
